# Generated by Django 4.2.6 on 2023-10-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('ust_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('unternehmensname', models.CharField(max_length=255)),
                ('land', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telefonnummer', models.CharField(max_length=20)),
                ('ansprechpartner', models.CharField(max_length=255)),
            ],
        ),
    ]
