# Generated by Django 4.2.7 on 2024-02-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akkuvariante',
            options={'verbose_name': 'Akkuvariante 1', 'verbose_name_plural': 'Akkuvarianten 1'},
        ),
    ]
