# Generated by Django 4.2.7 on 2023-11-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='ansprechpartner',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='land',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='telefonnummer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='unternehmensname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
