# Generated by Django 4.2.7 on 2024-02-06 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models
import home.storage
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InCartItem',
            fields=[
                ('item_nummer', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ust_id', models.CharField(max_length=50, null=True)),
                ('akkuvariante', models.CharField(max_length=255, null=True)),
                ('mit_120_Ohm_CAN_Bus_Widerstand', models.CharField(choices=[('Ja', 'Ja'), ('Nein', 'Nein')], default='Nein', max_length=255, null=True)),
                ('kabelvariante', models.CharField(max_length=255, null=True)),
                ('schnittstelle', models.CharField(max_length=255, null=True)),
                ('masse', models.CharField(max_length=255, null=True)),
                ('menge', models.FloatField(null=True)),
                ('original_preis', models.FloatField(null=True)),
                ('reduzierter_preis', models.FloatField(null=True)),
                ('gesamt', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='preisliste',
            options={},
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='gesamt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='menge',
        ),
        migrations.RemoveField(
            model_name='order',
            name='original_preis',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reduzierter_preis',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='image',
            field=models.ImageField(default='default.png', storage=home.storage.OverwriteStorage(), upload_to=home.models.get_img_upload_path_profile),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='plz',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='akkuvariante',
            name='akkuvariante_image_path',
            field=models.ImageField(default='default.png', storage=home.storage.OverwriteStorage(), upload_to=home.models.get_img_upload_path_akku),
        ),
        migrations.AlterField(
            model_name='kabelvariante',
            name='kabelvariante_image_path',
            field=models.ImageField(default='default.png', storage=home.storage.OverwriteStorage(), upload_to=home.models.get_img_upload_path_kabel),
        ),
        migrations.AlterField(
            model_name='kabelvariante',
            name='masse_image_path',
            field=models.ImageField(default='default.png', storage=home.storage.OverwriteStorage(), upload_to=home.models.get_img_upload_path_masse),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_datum',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_nummer',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Ordered', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schnittstelle',
            name='schnittstelle_image_path',
            field=models.ImageField(default='default.png', storage=home.storage.OverwriteStorage(), upload_to=home.models.get_img_upload_path_schnittstelle),
        ),
        migrations.AlterField(
            model_name='speziellebestellung',
            name='Status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='InCart', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='speziellebestellung',
            name='Ust_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='speziellebestellung',
            name='order_datum',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='uilabel',
            name='label_value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('item_nummer', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ust_id', models.CharField(max_length=50, null=True)),
                ('mit_120_Ohm_CAN_Bus_Widerstand', models.CharField(choices=[('Ja', 'Ja'), ('Nein', 'Nein')], default='Nein', max_length=255, null=True)),
                ('akkuvariante', models.CharField(max_length=255, null=True)),
                ('kabelvariante', models.CharField(max_length=255, null=True)),
                ('schnittstelle', models.CharField(max_length=255, null=True)),
                ('masse', models.CharField(max_length=255, null=True)),
                ('menge', models.FloatField(null=True)),
                ('original_preis', models.FloatField(null=True)),
                ('reduzierter_preis', models.FloatField(null=True)),
                ('gesamt', models.FloatField(null=True)),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='home.order')),
            ],
        ),
    ]
