# Generated by Django 4.2.7 on 2024-02-26 17:11

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import home.models
import home.storage
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_akkuvariante_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akkuvariante',
            options={'verbose_name': 'Akkuvariante', 'verbose_name_plural': 'Akkuvarianten'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Farbe', 'verbose_name_plural': 'Farben'},
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'Kundenprofil', 'verbose_name_plural': 'Kundenprofile'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Abbildung', 'verbose_name_plural': 'Abbildungen'},
        ),
        migrations.AlterModelOptions(
            name='incartitem',
            options={'verbose_name': 'Abbildung', 'verbose_name_plural': 'Abbildungen'},
        ),
        migrations.AlterModelOptions(
            name='kabelvariante',
            options={'verbose_name': 'Kabelvariante', 'verbose_name_plural': 'Kabelvarianten'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Bestellung', 'verbose_name_plural': 'Bestellungen'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Bestellten Artikel', 'verbose_name_plural': 'Bestellte Artikel'},
        ),
        migrations.AlterModelOptions(
            name='preisliste',
            options={'verbose_name': 'Preis', 'verbose_name_plural': 'Preisliste'},
        ),
        migrations.AlterModelOptions(
            name='schnittstelle',
            options={'verbose_name': 'Schnittstelle', 'verbose_name_plural': 'Schnittstellen'},
        ),
        migrations.AlterModelOptions(
            name='speziellebestellung',
            options={'verbose_name': 'Sonderlösung', 'verbose_name_plural': 'Sonderlösungen'},
        ),
        migrations.AlterModelOptions(
            name='uilabel',
            options={'verbose_name': 'UI-Label', 'verbose_name_plural': 'UI-Labels'},
        ),
        migrations.AlterField(
            model_name='color',
            name='color_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_value',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Farbcode'),
        ),
        migrations.AlterField(
            model_name='image',
            name='general_image_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='image',
            name='general_image_path',
            field=models.ImageField(default='default.png', storage=home.storage.OverwriteStorage(), upload_to=home.models.get_img_upload_path_general_images, verbose_name='Abbildungspfad'),
        ),
        migrations.AlterField(
            model_name='incartitem',
            name='item_nummer',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Artikelnummer'),
        ),
        migrations.AlterField(
            model_name='incartitem',
            name='masse',
            field=models.CharField(max_length=255, null=True, verbose_name='Maße'),
        ),
        migrations.AlterField(
            model_name='incartitem',
            name='original_preis',
            field=models.FloatField(null=True, verbose_name='Originalpreis'),
        ),
        migrations.AlterField(
            model_name='incartitem',
            name='reduzierter_preis',
            field=models.FloatField(null=True, verbose_name='Reduzierter Preis'),
        ),
        migrations.AlterField(
            model_name='kabelvariante',
            name='kabelvariante_image_path',
            field=models.ImageField(default='default.png', storage=home.storage.OverwriteStorage(), upload_to=home.models.get_img_upload_path_kabel, verbose_name='Abbildungspfad'),
        ),
        migrations.AlterField(
            model_name='kabelvariante',
            name='kabelvariante_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Kabelvariante'),
        ),
        migrations.AlterField(
            model_name='kabelvariante',
            name='main_part_min_length',
            field=models.IntegerField(null=True, verbose_name='Mindestlänge der Hauptleitung'),
        ),
        migrations.AlterField(
            model_name='kabelvariante',
            name='masse_image_path',
            field=models.ImageField(default='default.png', storage=home.storage.OverwriteStorage(), upload_to=home.models.get_img_upload_path_masse, verbose_name='Abbildungspfad für beschriftete Abbildung'),
        ),
        migrations.AlterField(
            model_name='kabelvariante',
            name='split_part_min_length',
            field=models.IntegerField(null=True, verbose_name='Mindestlänge der Zweigleitungen'),
        ),
        migrations.AlterField(
            model_name='kabelvariante',
            name='splits',
            field=models.IntegerField(null=True, verbose_name='Splits'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_nummer',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Bestellnummer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Angebot angefordert', 'Angebot angefordert'), ('Bestellt', 'Bestellt'), ('Geliefert', 'Geliefert'), ('Abgesagt', 'Abgesagt')], default='Bestellt', max_length=255, null=True, verbose_name='Bestellstatus'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_nummer',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Artikelnummer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='masse',
            field=models.CharField(max_length=255, null=True, verbose_name='Maße'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='home.order', verbose_name='Bestellung'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='original_preis',
            field=models.FloatField(null=True, verbose_name='Originalpreis'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='reduzierter_preis',
            field=models.FloatField(null=True, verbose_name='Reduzierter Preis'),
        ),
        migrations.AlterField(
            model_name='preisliste',
            name='gehause',
            field=models.CharField(max_length=50, null=True, verbose_name='Akkuvariante'),
        ),
        migrations.AlterField(
            model_name='preisliste',
            name='lange',
            field=models.CharField(max_length=50, null=True, verbose_name='Länge'),
        ),
        migrations.AlterField(
            model_name='preisliste',
            name='leitung',
            field=models.CharField(max_length=50, null=True, verbose_name='Schnittstelle'),
        ),
        migrations.AlterField(
            model_name='schnittstelle',
            name='schnittstelle_image_path',
            field=models.ImageField(default='default.png', storage=home.storage.OverwriteStorage(), upload_to=home.models.get_img_upload_path_schnittstelle, verbose_name='Abbildungspfad'),
        ),
        migrations.AlterField(
            model_name='schnittstelle',
            name='schnittstelle_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='speziellebestellung',
            name='hochgeladene_datei',
            field=models.FileField(null=True, upload_to='special_orders/', verbose_name='Hochgeladene Datei'),
        ),
        migrations.AlterField(
            model_name='speziellebestellung',
            name='order_nummer',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Bestellnummer'),
        ),
        migrations.AlterField(
            model_name='uilabel',
            name='label_key',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='uilabel',
            name='label_value',
            field=models.CharField(max_length=1000, null=True, verbose_name='Labelwert'),
        ),
    ]
