# Generated by Django 4.2.7 on 2024-01-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_customerprofile_email_customerprofile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InCartItem',
            fields=[
                ('item_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ust_id', models.CharField(max_length=50, null=True)),
                ('item_details', models.CharField(max_length=255, null=True)),
                ('quantity', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('InCart', 'In Cart'), ('Ordered', 'Ordered'), ('Delivered', 'Delivered')], default='InCart', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uilabel',
            name='label_value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
