# Generated by Django 4.2.7 on 2024-01-16 18:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_customerprofile_email_customerprofile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InCartItem',
            fields=[
                ('item_nummer', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ust_id', models.CharField(max_length=50, null=True)),
                ('mit_120_Ohm_CAN_Bus_Widerstand', models.CharField(max_length=255, null=True, choices=[('Ja','Ja'),('Nein','Nein')], default='Nein')),
                ('akkuvariante', models.CharField(max_length=255, null=True)),
                ('kabelvariante', models.CharField(max_length=255, null=True)),
                ('schnittstelle', models.CharField(max_length=255, null=True)),
                # ('item_details', models.CharField(max_length=255, null=True)),
                ('masse', models.FloatField(null=True)),
                ('original_preis', models.FloatField(null=True)),
                ('reduzierter_preis', models.FloatField(null=True)),
                ('gesamt', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='image',
            field=models.ImageField(default='General/default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('InCart', 'In Cart'), ('Bestellt', 'Bestellt'), ('Geliefert', 'Geliefert')], default='InCart', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uilabel',
            name='label_value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
