# Generated by Django 4.2.7 on 2024-02-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_akkuvariante_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incartitem',
            options={'verbose_name': 'Artikel im Warenkorb', 'verbose_name_plural': 'Artikel im Warenkorb'},
        ),
    ]
