# Generated by Django 4.2.7 on 2024-01-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_incartitem_alter_customerprofile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Delivered', 'Delivered')], default='Ordered', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('item_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ust_id', models.CharField(max_length=50, null=True)),
                ('mit_120_Ohm_CAN_Bus_Widerstand', models.CharField(max_length=255, null=True, choices=[('Ja','Ja'),('Nein','Nein')], default='Nein')),
                ('akkuvariante', models.CharField(max_length=255, null=True)),
                ('kabelvariante', models.CharField(max_length=255, null=True)),
                ('schnittstelle', models.CharField(max_length=255, null=True)),
                # ('item_details', models.CharField(max_length=255, null=True)),
                ('quantity', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
            ],
        ),
    ]
