# Generated by Django 4.2.7 on 2024-02-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_incartitem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='ust_id',
            new_name='benutzername',
        ),
        migrations.RenameField(
            model_name='incartitem',
            old_name='ust_id',
            new_name='benutzername',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ust_id',
            new_name='benutzername',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='ust_id',
            new_name='benutzername',
        ),
    ]
