# Generated by Django 4.2.7 on 2024-02-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_ust_id_customerprofile_benutzername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='ust_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
