# Generated by Django 4.2.7 on 2024-01-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_order_price_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
