# Generated by Django 4.2.7 on 2024-02-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_customerprofile_ust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incartitem',
            name='original_preis',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Originalpreis'),
        ),
        migrations.AlterField(
            model_name='incartitem',
            name='reduzierter_preis',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Reduzierter Preis'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='original_preis',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Originalpreis'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='reduzierter_preis',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Reduzierter Preis'),
        ),
    ]
