# Generated by Django 4.2.7 on 2024-01-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_specialorder_alter_preisliste_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='plz',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
